### ISSUE TITLE
Add OpenAPI spec and automatic API testing

### ISSUE THREAD

**Issue by queensferryme** [RSSerpent/RSSerpent#16]
We can use something like [schemathesis](https://github.com/schemathesis/schemathesis) to automatically test api endpoints. This test could also be added to `.github/workflows/docker.yaml` so that we could validate whether the built docker image could run without error.

**Comment by queensferryme** [comment]
Maybe also look into [snapshottest](https://github.com/syrusakbary/snapshottest).

**Comment by Stranger6667** [comment]
Hi! The schemathesis author here. If you'll have any questions about its integration, I'd be happy to help :)

**Comment by queensferryme** [comment]
@Stranger6667 Thanks a lot!
