### ISSUE TITLE
Install plugins in containers at runtime

### ISSUE THREAD

**Issue by queensferryme** [RSSerpent/RSSerpent#21]
Currently we have built docker images. However, rsserpent alone isn't of any practical use. We need to find a way to mount a `requirements.txt` into the container's file system, and install these required plugins at runtime.

Another possible approach is to let users build their own image based on the rsserpent image. This approach is technically easier to implement, but requires users to build their own image (which could be a serious problem for non-programmer users).

**Comment by queensferryme** [comment]
Suprisingly, using `pip` (instead of `poetry`) to install deps results in a ~5x smaller docker image (~300MB -> ~60MB), see 407fb03. However, this will require users exporting `poetry.lock` to `requirements.txt` before building docker images.

I think ~60MB image size is good enough, so I remove `docker-slim` things from the workflow.

/cc @EurusEurus in case he/she is interested.

**Comment by queensferryme** [comment]
Well, now we can install plugins in containers at runtime.

Suppose you have a a list of rsserpent plugins in `/path/to/some/directory/requirements.txt`, you can run
```
docker run -d -p 8000:8000 -v /path/to/some/directory:/app/runtime queensferry/rsserpent:master
```

The [`docker-entrypoint.sh`](https://github.com/RSSerpent/RSSerpent/blob/456c35c075e49f08ca86645face09d25c0e283b6/scripts/docker-entrypoint.sh) will check if there is any `/app/runtime/requirements.txt` and install them with `pip install -r`, then run `uvicorn rsserpent:app --host 0.0.0.0` to start RSSerpent.

**Comment by EurusEurus** [comment]
> Suprisingly, using `pip` (instead of `poetry`) to install deps results in a ~5x smaller docker image (~300MB -> ~60MB), see [407fb03](https://github.com/RSSerpent/RSSerpent/commit/407fb0315d984fd9af1d00756b08a5cfa108c760). However, this will require users exporting `poetry.lock` to `requirements.txt` before building docker images.
> 
> I think ~60MB image size is good enough, so I remove `docker-slim` things from the workflow.
> 
> /cc @EurusEurus in case he/she is interested.

SGTM Simple and convenient is the first choice.
