### ISSUE TITLE
docker build err

### ISSUE THREAD

**Issue by wdssmq** [RSSerpent/RSSerpent#29]
Step 7/17 : COPY --chown=app:app poetry.lock pyproject.toml .
When using COPY with more than one source file, the destination must be a directory and end with a /

**Comment by queensferryme** [comment]
Please provide more information about your OS (macOS/Windows/Linux) and docker version etc.

At least `docker build` works well on my machine & GitHub [Actions](https://github.com/RSSerpent/RSSerpent/blob/87a152a8e5e3b3ca1aec1f2d7148ea30cbb88f6f/.github/workflows/docker.yaml).

**Comment by queensferryme** [comment]
This might have been fixed in 3cffd0f. Please verify.

https://github.com/RSSerpent/RSSerpent/blob/3cffd0faac0089e7447901316f02f246f9a4fc60/Dockerfile#L11
